apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: obc-template
  title: Add OBC to an existing project
  description: Add OBC to an existing project
  tags:
    - obc
spec:
  owner: janus-authors
  system: janus-idp
  type: service

  parameters:
    - title: Provide information about the existing component
      required:
        - sourceControl
        - orgName
        - repoName
      properties:
        sourceControl:
          title: Source Control
          type: string
          enum:
            - github.com
            - gitlab.com
          enumNames:
            - GitHub
            - GitLab
        orgName:
          title: Organization Name
          type: string
        repoName:
          title: Repository Name
          type: string
        componentName:
          title: Component Name
          type: string
          description: Attach the manifests to an existing component
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Component
    - title: Provide information about the new component
      required:
        - owner
        - system
        - storageClassName
      properties:
        owner:
          title: Owner
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - Group
                - User
        system:
          title: System
          type: string
          ui:field: EntityPicker
          ui:options:
            catalogFilter:
              kind:
                - System
        storageClassName:
          title: Storage Class Name
          type: string
          description: Storage Class Name of the OBC
  steps:
    - id: catalogTemplate
      name: Generating the Catalog Info Component
      action: fetch:template
      input:
        url: ../../scaffolder-skeletons/catalog-info-skeleton/
        values:
          # Gitops specific values
          entityKind: Resource
          partOf: ${{ parameters.componentName }}

          # Normal values
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}-gitops
          sourceControl: ${{ parameters.sourceControl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the manifests for ${{ parameters.repoName }}

    - id: manifestsTemplate
      name: Generating the Manifests Component
      action: fetch:template
      input:
        url: ./skeleton
        values:
          orgName: ${{ parameters.orgName }}
          repoName: ${{ parameters.repoName }}
          sourceControl: ${{ parameters.sourceControl }}
          owner: ${{ parameters.owner }}
          system: ${{ parameters.system }}
          applicationType: gitops
          description: Contains the manifests for ${{ parameters.repoName }}
          storageClassName: ${{ parameters.storageClassName }}

    # Give publish:github and publish:gitlab the same id so
    # that we don't need if statements in the register step
    - id: publish
      if: ${{ parameters.sourceControl == 'github.com' }}
      name: Publishing to the Source Code Repository
      action: publish:github
      input:
        allowedHosts: ['github.com']
        description: Contains the manifests for ${{ parameters.repoName }}
        repoUrl: github.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}-gitops
        defaultBranch: main

    - id: publish
      if: ${{ parameters.sourceControl == 'gitlab.com' }}
      name: Publishing to the Source Code Repository
      action: publish:gitlab
      input:
        allowedHosts: ['gitlab.com']
        description: Contains the manifests for ${{ parameters.repoName }}
        repoUrl: gitlab.com?owner=${{ parameters.orgName }}&repo=${{ parameters.repoName }}-gitops
        defaultBranch: main

    - id: register
      name: Registering the Catalog Info Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Open the Source Code Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open the Catalog Info Component
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
